using LDY.CSharp.LINQ.DataProvider;
using LDY.CSharp.LINQ.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LDY.CSharp.LINQ {
    public class Extensions {
        private IData Data;

        public Extensions(IData data) {
            Data = data;
        }

        /// <summary>
        /// https://docs.microsoft.com/en-gb/dotnet/api/system.linq.enumerable.select?view=netcore-2.2
        /// Select: Projects each element of a sequence into a new form.
        /// </summary>
        public void Select() {
            WebSite webSite = Data.GetWebSite();
            // lambda
            bool[] arePagesHaveOneLanguage = webSite.Pages.Select(page => page.Languages.Count == 1).ToArray();
            // full 

        }

        //Where: ...

        //OrderBy: ...

        //OrderByDescending: ...

        //ThenBy: ...

        //ThenByDescending: ...

        //Join: ...

        //GroupBy: ...

        //ToLookup: ...

        //GroupJoin: ...

        //Reverse: ...

        //All: ...

        //Any: ...

        //Contains: ...

        //Distinct: ...

        //Except: ...

        //Union: ...

        //Intersect: ...

        //Count: ...

        //Sum: ...

        //Average: ...

        //Min: ...

        //Max: ...

        //Take: ...

        //Skip: ...

        //TakeWhile: ...

        //SkipWhile: ...

        //Concat: ...

        //Zip: ...

        //First: ...

        //FirstOrDefault: ...

        public void FirstOrDefault() {

        }

        //Single: ...

        //SingleOrDefault: ...

        //ElementAt: ...

        //ElementAtOrDefault: ...

        //Last: ...

        //LastOrDefault: ...
    }
}
